# Generated by Django 5.2.8 on 2025-12-11 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cv_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('issuer', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='api.cv')),
            ],
            options={
                'db_table': 'cv_awards',
                'ordering': ['order', '-year'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('proficiency', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='api.cv')),
            ],
            options={
                'db_table': 'cv_languages',
                'ordering': ['order', 'name'],
            },
        ),
    ]
