# Generated by Django 5.2.8 on 2025-12-13 12:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_cv_updated_at_award_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='labbooking',
            name='imac_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Specific iMac number (1–30)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AddField(
            model_name='labbooking',
            name='time_slot',
            field=models.CharField(blank=True, help_text='Time slot label, e.g. "09:00-11:00"', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='equipmentrental',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='labbooking',
            index=models.Index(fields=['lab', 'booking_date', 'time_slot', 'imac_number'], name='lab_booking_lab_id_879231_idx'),
        ),
        migrations.AddIndex(
            model_name='labbooking',
            index=models.Index(fields=['student', 'booking_date', 'time_slot'], name='lab_booking_student_e99d8b_idx'),
        ),
    ]
