# Generated by Django 5.2.8 on 2025-12-24 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_labbooking_imac_number_labbooking_time_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentrental',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmentrental',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmentrental',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_equipment_rentals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipmentrental',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_rentals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipmentrental',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('damaged', 'Damaged')], default='pending', max_length=20),
        ),
    ]
