# Generated by Django 5.2.8 on 2025-12-24 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_equipmentrental_reject_reason_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentrental',
            options={},
        ),
        migrations.AddField(
            model_name='equipmentrental',
            name='duration_days',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='equipmentrental',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentrental',
            name='expected_return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentrental',
            name='rental_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentrental',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_rentals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipmentrental',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('damaged', 'Damaged')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipmentrental',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='equipmentrental',
            table=None,
        ),
    ]
