# Generated by Django 5.2.8 on 2026-01-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_equipmentcategory_equipmentcategorymapping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='quantity_under_maintenance',
            field=models.IntegerField(default=0),
        ),
    ]
